#!/bin/bash
#SBATCH --job-name=makecal
#SBATCH --account=PAS2340
#SBATCH --time=48:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=12

# you can tell the script which SCA to use by setting:
#
# sbatch --export=USE_SCA=06 make_sca_files_2026Jul.job
#
# (this way you don't need to modify the script to run any of the SCAs)
# which SCA to use? (format: '01' .. '18' -- you are supposed to have the leading 0 for SCA<=9)

# which read pattern to use? (format: string)
export READ_PATTERN_NAME="IM_107_8"
# tag for this set of files (should be the same for all the SCAs)
export TAG="DUMMY20260726"

# MAST directory
export MAST_DL_DIR=/fs/scratch/PCON0003/cond0007/from_mast
# where we are sending the data
export TARGET_DIR=/fs/scratch/PCON0003/cond0007/cal_2026_Jul/$USE_SCA
# where these scripts are located -- could be changed if needed
export SCRIPT_DIR=$SLURM_SUBMIT_DIR


cd $SLURM_SUBMIT_DIR

# tell the log some information
echo "--- Environment variable ---"
echo "USE_SCA" $USE_SCA
echo "READ_PATTERN_NAME" $READ_PATTERN_NAME
echo "TAG" $TAG
echo "MAST_DL_DIR" $MAST_DL_DIR
echo "TARGET_DIR" $TARGET_DIR
echo "SCRIPT_DIR" $SCRIPT_DIR
echo " "

# Map the files to their new locations
mkdir $TARGET_DIR
perl mapping.pl $TARGET_DIR

# set up solid-waffle
# This is for using 50 exposures.
pwd
echo "" > summary_files_$USE_SCA.txt; rm summary_files_$USE_SCA.txt # suppress warning
perl write_solid-waffle_config.pl $TARGET_DIR $USE_SCA  1 10 > config1_$USE_SCA.txt
perl write_solid-waffle_config.pl $TARGET_DIR $USE_SCA 11 20 > config2_$USE_SCA.txt
perl write_solid-waffle_config.pl $TARGET_DIR $USE_SCA 21 30 > config3_$USE_SCA.txt
perl write_solid-waffle_config.pl $TARGET_DIR $USE_SCA 31 40 > config4_$USE_SCA.txt
perl write_solid-waffle_config.pl $TARGET_DIR $USE_SCA 41 50 > config5_$USE_SCA.txt
# write test script
echo "import sys" > test_run.py
echo "from solid_waffle.correlation_run import run_ir_all" >> test_run.py
echo "run_ir_all(sys.argv[1])" >> test_run.py
# run solid-waffle
# This step can be parallelized
python test_run.py $SCRIPT_DIR/config1_$USE_SCA.txt > $TARGET_DIR/sw-SCA$USE_SCA-P1.log &
python test_run.py $SCRIPT_DIR/config2_$USE_SCA.txt > $TARGET_DIR/sw-SCA$USE_SCA-P2.log &
python test_run.py $SCRIPT_DIR/config3_$USE_SCA.txt > $TARGET_DIR/sw-SCA$USE_SCA-P3.log &
python test_run.py $SCRIPT_DIR/config4_$USE_SCA.txt > $TARGET_DIR/sw-SCA$USE_SCA-P4.log &
python test_run.py $SCRIPT_DIR/config5_$USE_SCA.txt > $TARGET_DIR/sw-SCA$USE_SCA-P5.log &
wait
# cleanup files (these are stored in cal)
rm $SCRIPT_DIR/config?_$USE_SCA.txt
rm test_run.py

# now print the gain files
pwd
python make_gain_file.py summary_files_$USE_SCA.txt $USE_SCA $TARGET_DIR/roman_wfi_gain_$TAG\_SCA$USE_SCA.asdf
# this is no longer needed
rm summary_files_$USE_SCA.txt

# run the noise script
python -m solid_waffle.noise_run -f 1 -i $TARGET_DIR/99999999_SCA$USE_SCA\_Noise_001.fits -o $TARGET_DIR/noise_SCA$USE_SCA.fits -n 100 -t 3 -cd 5.0 -rh 7 -tn 34 -ro
# here:
# 6 = file format (consistent with FPS)
# $TARGET_DIR/99999999_SCA$USE_SCA\_Noise_001.fits = name of first noise file
# $TARGET_DIR/noise_SCA$USE_SCA.fits = output file
# 100 = number of darks
# 2 = frame to start dark current determination (Fortran ordered since it is a FITS file)
# 5.0 = cutoff for 'low CDS' pixel
# 7 = row overhead (placeholder, not actually propagated into the reference files)
# 34 = number of frames to use for 'total' noise and dark current determination
# -ro = include reference output in build

# and generate histograms for the DNL
python -m solid_waffle.histograms -f 1 -i $TARGET_DIR/99999999_SCA$USE_SCA\_Noise_001.fits -o $TARGET_DIR/histD_SCA$USE_SCA.dat -n 100
python -m solid_waffle.histograms -f 1 -i $TARGET_DIR/99999999_SCA$USE_SCA\_LoFlat_001.fits -o $TARGET_DIR/histG_SCA$USE_SCA.dat -n 50
python -m solid_waffle.histograms -f 1 -i $TARGET_DIR/99999999_SCA$USE_SCA\_Flat_001.fits -o $TARGET_DIR/histF_SCA$USE_SCA.dat -n 50

# build the dark file for this read pattern
echo "---" > settings_$READ_PATTERN_NAME.yaml
echo "READS: [0, 1, 1, 2, 2, 4, 4, 10, 10, 26, 26, 32, 32, 34, 34, 35]" >> settings_$READ_PATTERN_NAME.yaml
echo "..." >> settings_$READ_PATTERN_NAME.yaml
python make_dark_file.py $READ_PATTERN_NAME $TARGET_DIR/99999999_SCA$USE_SCA\_Noise_001.fits $TARGET_DIR/noise_SCA$USE_SCA.fits $USE_SCA $TARGET_DIR/roman_wfi_dark_$TAG\_SCA$USE_SCA.asdf

# build the linearity files
perl write_linearity_config.pl $TARGET_DIR $USE_SCA $TAG > linearity_pars_$USE_SCA.json
python -m solid_waffle.linearity_run $SCRIPT_DIR/linearity_pars_$USE_SCA.json

# post-process these to get pflat and saturation
python postprocess_calfiles.py $TARGET_DIR/roman_wfi_linearitylegendre_$TAG\_SCA$USE_SCA.asdf $USE_SCA $READ_PATTERN_NAME
python makemask.py $TARGET_DIR/roman_wfi_mask_$TAG\_SCA$USE_SCA.asdf $USE_SCA $READ_PATTERN_NAME
rm settings_$READ_PATTERN_NAME.yaml
